import os, re
from pathlib import Path
from collections import defaultdict

roots = [
    Path(os.path.expanduser("~/.codex/skills")),
    Path(os.path.expanduser("~/.agents/skills")),
]

# === 要排除的开发/编码类别 (这些 skill 全是写代码用的) ===
EXCLUDE_PATTERNS = [
    # 纯编码开发
    "agent-harness-construction", "agent-introspection-debugging", "agent-sort",
    "agentic-engineering", "agentic-os", "ai-first-engineering", "ai-regression-testing",
    "agent-browser", "agent-reach", "browser-act", "autonomous-loops",
    "continuous-agent-loop", "enterprise-agent-ops", "non-execution-task",
    "think-then-act", "v4-best-practices", "workspace-surface-audit",
    "council", "delegate", 
    # 后端/全栈
    "aspnet-core", "nodejs-keccak256", "waza", "waza-interactive",
    "api-connector-builder", "api-design", "mcp-builder",
    "claude-api", "claude-devfleet", "x-api",
    # CLI/工具开发
    "cli-creator", "code-explainer", "code-tour", "codebase-migrate",
    "error-handling", "regex-vs-llm-structured-text",
    "backend-patterns", "docker-patterns", "deployment-patterns",
    "database-migrations", "database-design",
    # 测试
    "e2e-testing", "eval-harness", "evaluator-optimizer",
    "playwright", "playwright-interactive", "tdd-workflow",
    "webapp-testing", "windows-desktop-e2e", "iterative-retrieval",
    "swift-protocol-di-testing", "ralphinho-rfc-pipeline",
    # 审查
    "diff-reviewer", "preflight-reviewer", "test-reviewer",
    "plan-reviewer", "permission-reviewer", "review-gate",
    "pr-review-ci-fix", "gh-fix-ci", "gh-address-comments",
    # 安全
    "security-review", "security-scan", "security-threat-model",
    "security-best-practices", "security-bounty-hunter", "security-ownership-map",
    "django-security", "springboot-security", "laravel-security",
    "perl-security", "quarkus-security", "hipaa-compliance",
    "healthcare-phi-compliance", "defi-amm-security",
    "llm-trading-agent-security", "evm-token-decimals",
    # Git/CI
    "github-ops", "gh-fix-ci", "gh-address-comments",
    "git-workflow-automator", "github-starred-manager",
    # 部署
    "cloudflare-deploy", "deploy-pipeline", "netlify-deploy",
    "render-deploy", "vercel-deploy", "docker-compose",
    # 数据库
    "clickhouse-io", "postgres-patterns", "mysql-patterns",
    "prisma-patterns", "jpa-patterns", 
    # 网络
    "cisco-ios-patterns", "netmiko-ssh-automation", "network-bgp-diagnostics",
    "network-config-validation", "network-interface-health", "traffic-engineering",
    "homelab-network-readiness", "homelab-network-setup", "optimize-network",
    # iOS/Swift
    "swift-actor-persistence", "swift-concurrency-6-2", "swiftui-patterns",
    # Skill/插件管理
    "skill-creator", "skill-installer", "skill-scout", "skill-stocktake",
    "skill-share", "plugin-creator", "hookify-rules", "migrate-to-codex",
    "configure-ecc", "ecc-skill-index", "ecc-tools-cost-audit",
    "release-skills",
    # 成本/监控
    "cost-aware-llm-pipeline", "cost-tracking", "token-budget-advisor",
    "sentry", "sentry-triage", "issue-triage", "datadog-logs",
    # 集成/开发
    "connect", "connect-apps", "connections-optimizer",
    "jira-integration", "linear", "notion-",
    "notion-spec-to-implementation",
    "google-workspace-ops",
    # 系统/自动化
    "automation-audit-ops", "terminal-ops",
    # 验证编译
    "compile-and-verify", "verification-loop",
    # 上下文压缩(开发用)
    "context-compressor", "strategic-compact",
    # 其他纯开发
    "nanoclaw-repl",
    "team-builder", "scientific-pkg-gget", "scrapling",
    "web-artifacts-builder", "ui-demo", "ds-tui-iteration-engineer",
    "claude-devfleet", "plankton-code-quality",
    "nodejs-keccak256", "foundation-models-on-device",
    "continuous-learning", "continuous-learning-v2",
    "keep-codex-fast",
    "production-audit", "evaluator-optimizer",
    # DBS部分(保留核心,去掉开发向)
    "dbs-agent-mesh", "dbs-agent-migration", "dbs-orchestrator",
    "dbs-benchmark",
    "hyperframes-cli",
    "hyperframes-registry",
    "search-first",
    "getting-started",
]

# === 中文名称映射 ===
CN_NAMES = {
    "stop-slop": "AI废话消除",
    "ai-taste-check": "AI味诊断",
    "humanizer": "去AI味改写",
    "shuorenhua": "说人话降重",
    "prompt-optimizer": "提示词优化",
    "article-writing": "深度写作",
    "viral-writer-skill": "爆款写作",
    "content-engine": "内容引擎",
    "content-creation-workflow": "内容生产流程",
    "crosspost": "多平台分发",
    "baoyu-post-to-wechat": "公众号发布",
    "baoyu-post-to-x": "X/Twitter发布",
    "baoyu-post-to-weibo": "微博发布",
    "baoyu-translate": "三模式翻译",
    "baoyu-cover-image": "封面图生成",
    "baoyu-image-gen": "图片生成(废弃)",
    "baoyu-comic": "漫画生成",
    "baoyu-diagram": "图表生成",
    "baoyu-infographic": "信息图生成",
    "baoyu-slide-deck": "PPT卡片",
    "baoyu-format-markdown": "Markdown格式化",
    "baoyu-markdown-to-html": "Markdown转HTML",
    "baoyu-url-to-markdown": "网页转Markdown",
    "baoyu-wechat-summary": "群聊摘要",
    "baoyu-compress-image": "图片压缩",
    "baoyu-youtube-transcript": "YouTube转录",
    "baoyu-xhs-images": "小红书配图(废弃)",
    "deep-research": "深度调研",
    "market-research": "市场分析",
    "exa-search": "神经搜索",
    "search-first": "搜索优先",
    "figma": "Figma设计",
    "figma-implement-design": "设计稿转代码",
    "figma-generate-design": "设计稿生成",
    "frontend-design": "前端页面设计",
    "canvas-design": "画布设计",
    "algorithmic-art": "算法艺术",
    "manim-video": "数学动画视频",
    "remotion-video-creation": "React视频制作",
    "video-editing": "视频剪辑",
    "transcribe": "语音转录",
    "speech": "文字转语音",
    "general-video": "通用视频制作",
    "slideshow": "幻灯片视频",
    "talking-head-recut": "口播精剪",
    "motion-graphics": "动态图形设计",
    "product-launch-video": "产品发布视频",
    "music-to-video": "音乐配视频",
    "pr-to-video": "PR转视频",
    "website-to-video": "网页转视频",
    "hyperframes": "Hyperframes动画",
    "blender-motion-state-inspection": "Blender动画检查",
    "pdf": "PDF处理",
    "pptx": "PPT编辑",
    "xlsx": "Excel处理",
    "docx": "Word处理",
    "spreadsheets": "电子表格",
    "presentations": "演示文稿",
    "documents": "文档编辑",
    "nutrient-document-processing": "高级文档处理",
    "feishu": "飞书集成",
    "session-memory": "会话记忆",
    "knowledge-ops": "知识管理",
    "knowledge-base": "知识库",
    "jacky-motion": "科普动画HTML",
    "guizang-social-card-skill": "小红书卡片",
    "guizang-ppt-skill": "PPT生成",
    "khazix-writer": "卡兹克写作",
    "neat-freak": "洁癖整理",
    "hv-analysis": "横纵分析",
    "storage-analyzer": "磁盘清理",
    "aihot": "AI热点日报",
    "ian-xiaohei-illustrations": "小黑插画",
    "weread-skills": "微信读书",
    "weread-exporter": "读书笔记导出",
    "screenshot": "屏幕截图",
    "scientific-thinking-literature-review": "文献综述",
    "scientific-thinking-scholar-evaluation": "学者评估",
    "pubmed-database": "PubMed检索",
    "uspto-database": "专利检索",
    "academic-paper-composer": "论文写作",
    "academic-paper-strategist": "论文策略",
    "lead-intelligence": "销售线索分析",
    "lead-research-assistant": "客户调研",
    "carrier-relationship-management": "运营商管理",
    "customer-billing-ops": "账单运营",
    "customs-trade-compliance": "贸易合规",
    "energy-procurement": "能源采购",
    "finance-billing-ops": "收入分析",
    "inventory-demand-planning": "库存管理",
    "logistics-exception-management": "物流管理",
    "production-scheduling": "生产排程",
    "quality-nonconformance": "质量管理",
    "returns-reverse-logistics": "逆向物流",
    "email-ops": "邮箱工作流",
    "email-customer": "客户邮件",
    "internal-comms": "内部沟通",
    "messages-ops": "实时消息",
    "unified-notifications-ops": "统一通知",
    "investor-materials": "投资人材料",
    "investor-outreach": "投资人邮件",
    "product-capability": "产品功能路由",
    "project-flow-ops": "项目执行",
    "brand-voice": "品牌语调",
    "brand-guidelines": "Anthropic品牌",
    "theme-factory": "主题设计",
    "liquid-glass-design": "毛玻璃UI",
    "dbs": "DBS核心",
    "dbs-action": "DBS行动",
    "dbs-decision": "DBS决策",
    "dbs-goal": "DBS目标",
    "dbs-learning": "DBS学习",
    "dbs-report": "DBS报告",
    "dbs-save": "DBS保存",
    "dbs-restore": "DBS恢复",
    "dbs-hook": "DBS钩子",
    "dbs-chatroom": "定向聊天室",
    "dbs-content-system": "DBS内容系统",
    "dbs-diagnosis": "DBS诊断",
    "dbs-deconstruct": "DBS解构",
    "dbs-good-question": "DBS好问题",
    "dbs-slowisfast": "DBS慢即快",
    "dbs-resonate": "DBS共鸣",
    "dbs-spread": "DBS传播",
    "dbs-ai-check": "DBS质量审核",
    "dbs-xhs-title": "DBS小红书标题",
    "dbs-wechat-html": "DBS公众号排版",
    "faith-booknote": "Faith读书笔记",
    "faith-viral-write": "Faith爆款写作",
    "faith-context-compress": "Faith上下文",
    "faith-session": "Faith会话",
    "faith-skill-architect": "Faith技能架构",
    "faith-skill-deploy": "Faith技能部署",
    "faith-skill-distill": "Faith技能蒸馏",
    "faith-skill-factory": "Faith技能工厂",
    "faith-skill-solution": "Faith技能方案",
    "faith-kb-scan": "Faith知识库",
    "faith-pipeline": "Faith流水线",
    "faith-pipeline-audit": "Faith流水线审计",
    "faith-prompt-compile": "Faith提示词编译",
    "faith-gate-check": "Faith质量门",
    "faith-truth-check": "Faith事实核查",
    "faith-index": "Faith索引",
    "faith-workflow": "Faith工作流",
    "faith-humanizer": "Faith人性化",
    "ljg-think": "深度思考",
    "ljg-writes": "结构化写作",
    "ljg-book": "拆书解读",
    "ljg-card": "知识卡片",
    "ljg-invest": "投资分析",
    "ljg-learn": "深度学习方法论",
    "ljg-paper": "论文全流程",
    "ljg-present": "演讲指导",
    "ljg-qa": "问答生成",
    "ljg-read": "深度阅读",
    "ljg-relationship": "人际管理",
    "ljg-roundtable": "圆桌讨论",
    "ljg-skill-map": "技能图谱",
    "ljg-travel": "旅行规划",
    "ljg-word": "单词学习",
    "ljg-paper-flow": "论文流管理",
    "ljg-paper-river": "论文并行管理",
    "ljg-plain": "化繁为简",
    "ljg-push": "执行力推动",
    "ljg-rank": "优先级排序",
    "ljg-word-flow": "词汇学习系统",
    "last30days": "30天热议",
    "standup-solo": "每日站会",
    "ship-decision": "发布决策",
    "postmortem-solo": "事后复盘",
    "launch-tweet": "发布推文",
    "domain-name-brainstormer": "域名头脑风暴",
    "competitive-ads-extractor": "广告素材分析",
    "superpowers-zh": "超级力量",
    "paperjsx": "Office文档生成",
    "geju": "格局思维",
    "snake-perspective": "蛇视角思维",
    "slug-generator": "短链接生成",

    "baoyu-article-illustrator": "文章配图",
    "baoyu-danger-gemini-web": "Gemini生成",
    "baoyu-danger-x-to-markdown": "推文转MD",
    "baoyu-image-cards": "图文卡片",
    "baoyu-imagine": "创意图像",
    "blueprint": "蓝图规划",
    "brand-guidelines": "Anthropic品牌",
    "career-ops": "职业运营",
    "content-guard": "内容门禁",
    "content-hash-cache-pattern": "内容去重",
    "content-research-writer": "研究型写作",
    "content-reverse": "逆向拆解",
    "create-plan": "计划生成",
    "customer-billing-ops": "账单运营",
    "dashboard-builder": "仪表盘",
    "dbs-content": "DBS内容",
    "email-ops": "邮箱工作流",
    "fal-ai-media": "AI媒体",
    "finance-billing-ops": "收入分析",
    "getting-started": "快速上手",
    "helium-mcp": "氦气搜索",
    "internal-comms": "内部沟通",
    "jupyter-notebook": "Jupyter分析",
    "lead-intelligence": "销售线索",
    "liquid-glass-design": "毛玻璃UI",
    "messages-ops": "实时消息",
    "notion-knowledge-capture": "Notion笔记",
    "notion-meeting-intelligence": "会议准备",
    "notion-research-documentation": "Notion研究",
    "notion-spec-to-implementation": "Notion需求",
    "planning-with-files": "文件规划",
    "product-capability": "PRD转计划",
    "project-flow-ops": "项目执行",
    "research-ops": "实时调研",
    "scientific-db-pubmed-database": "PubMed检索",
    "scientific-db-uspto-database": "USPTO专利",
    "seo": "SEO优化",
    "slack-gif-creator": "Slack动图",
    "social-graph-ranker": "社交排序",
    "task-capsule-builder": "任务胶囊",
    "team-builder": "团队配置",
    "theme-factory": "主题工厂",
    "understand": "代码理解",
    "understand-diff": "变更理解",
    "unified-notifications-ops": "统一通知",
    "videodb": "视频理解",
    "visa-doc-translate": "签证翻译",
    "wewrite": "公众号助手",
    "windows-file-system-organizer": "文件整理",
    "windows-performance-optimizer": "性能优化",
    "yeet": "Git一键流程",}

# === 中文简介 (作用 + 触发词) ===
CN_DESC = {
    "stop-slop": "检测并消除AI生成文本中的废话、冗余和空洞表达",
    "ai-taste-check": "AI味深度诊断与修复：拆根因/给对策/出成品/附自检报告，内容输出前最后一道质检",
    "humanizer": "将AI生成文本改写得更自然，消除机器翻译感和重复句式",
    "shuorenhua": "对论文/文章去AI痕迹改写，降低查重率，让文风像人写的",
    "prompt-optimizer": "优化提示词使其更精准结构化，分析优化前后差异",
    "article-writing": "根据笔记/语音/资料写深度长文，逻辑严密可读性强",
    "viral-writer-skill": "写有传播力的公众号/社交媒体文章，标题有吸引力",
    "content-engine": "平台原生内容系统：为X/LinkedIn/TikTok/YouTube/Newsletter创建内容体系",
    "content-creation-workflow": "自媒体全流程v6：搜索+红队+去AI味+质检+主编协作+MED模式",
    "crosspost": "多平台分发：将内容适配分发到X/LinkedIn/Threads/Bluesky",
    "baoyu-post-to-wechat": "公众号发布：通过API或CDP将内容发布到微信公众号",
    "baoyu-post-to-x": "X/Twitter发布：支持普通推文(图片/视频)和X长文",
    "baoyu-post-to-weibo": "微博发布：支持普通微博和头条文章发布",
    "baoyu-translate": "三模式翻译：快速(直接)/标准(分析后译)/高级(全文优化)",
    "baoyu-cover-image": "封面图生成：5维度(类型/配色/渲染/文字/风格)×11色板×8渲染",
    "baoyu-image-gen": "[已废弃]多模型AI图像生成，建议使用baoyu-imagine替代",
    "baoyu-comic": "把故事/脚本生成漫画分镜和画面",
    "baoyu-diagram": "专业SVG图表：暗色主题架构图/流程图/序列图/结构图",
    "baoyu-infographic": "将数据/信息制作成信息图，突出重点",
    "baoyu-slide-deck": "幻灯片图片生成：从内容生成大纲→风格说明→逐页图片",
    "baoyu-format-markdown": "格式化为规范Markdown，优化标题层级排版",
    "baoyu-markdown-to-html": "Markdown转微信HTML：支持代码高亮/数学/PlantUML/注脚/表格",
    "baoyu-url-to-markdown": "抓取URL内容转为结构化Markdown",
    "baoyu-wechat-summary": "微信群聊亮点摘要：将微信群聊记录整理为结构化精华摘要",
    "baoyu-compress-image": "压缩图片到指定大小，保持画质减小文件",
    "baoyu-youtube-transcript": "下载YouTube字幕/转录并总结要点",
    "baoyu-xhs-images": "[已废弃]小红书信息图卡片系列，建议使用baoyu-image-cards替代",
    "deep-research": "对主题深度调研，多源交叉验证输出研究报告",
    "market-research": "对市场/赛道竞争分析，含主要玩家/差异化/趋势",
    "exa-search": "用神经搜索找最新资料，过滤低质量来源",
    "search-first": "执行操作前先搜索确认最佳实践和最新方案",
    "figma": "Figma设计上下文：获取设计稿/截图/变量/素材，支持设计稿转前端代码",
    "figma-implement-design": "将Figma设计稿转前端代码，像素级还原",
    "figma-generate-design": "根据需求描述生成Figma设计稿",
    "frontend-design": "根据描述创建前端页面，含交互和动画",
    "canvas-design": "在Canvas创建视觉设计/海报",
    "algorithmic-art": "用算法生成艺术作品",
    "manim-video": "生成数学/科学动画视频",
    "remotion-video-creation": "用React代码创建可编程视频/动画",
    "video-editing": "编辑视频：剪切/合并/字幕/转场",
    "transcribe": "将音频/视频转录为文字，支持时间戳",
    "speech": "文字转语音或语音转文字",
    "general-video": "创建通用视频：口播/教程/宣传片",
    "slideshow": "创建16:9幻灯片视频，带转场和音乐",
    "talking-head-recut": "对口播视频精剪，优化节奏画面",
    "motion-graphics": "创建MG动画/动态图形",
    "product-launch-video": "制作产品发布宣传视频",
    "music-to-video": "为音乐创建匹配视觉内容",
    "pr-to-video": "从PR描述生成更新视频",
    "website-to-video": "把网页内容转化为视频解说",
    "hyperframes": "用Hyperframes框架创建动画视频",
    "blender-motion-state-inspection": "检查Blender项目动画状态",
    "pdf": "处理PDF：读取/提取/合并/格式转换",
    "pptx": "创建编辑PPT：布局/图表/动画",
    "xlsx": "处理Excel：数据分析/图表/公式",
    "docx": "创建编辑Word文档：排版/目录/审阅",
    "spreadsheets": "创建编辑电子表格，数据分析可视化",
    "presentations": "创建演示文稿，支持模板和设计",
    "documents": "创建编辑文档，多格式协作",
    "nutrient-document-processing": "高级文档处理SDK",
    "feishu": "飞书API：文档/表格/消息/审批操作",
    "session-memory": "跨会话记忆，记住之前讨论和决策",
    "knowledge-ops": "管理知识库：创建/组织/检索",
    "knowledge-base": "构建维护结构化知识库",
    "jacky-motion": "把中文口播稿变成16:9信息动画HTML",
    "guizang-social-card-skill": "生成小红书风格卡片：多图排版",
    "guizang-ppt-skill": "从大纲生成完整PPT",
    "khazix-writer": "用卡兹克风格和节奏创作长文",
    "neat-freak": "任务后自动对齐代码/文档/记忆",
    "hv-analysis": "对产品/公司/概念横纵分析输出报告",
    "storage-analyzer": "扫描磁盘空间，三色分级清理建议",
    "aihot": "查询AI HOT日报，最新行业动态",
    "ian-xiaohei-illustrations": "生成Ian小黑风格插画",
    "weread-skills": "微信读书Skill集：导出/分析/笔记",
    "weread-exporter": "导出微信读书笔记和划线",
    "screenshot": "截取屏幕区域或页面保存分析",
    "scientific-thinking-literature-review": "系统性文献综述：检索到批判性综合",
    "scientific-thinking-scholar-evaluation": "学者学术影响力评估",
    "pubmed-database": "PubMed数据库检索和文献管理",
    "uspto-database": "USPTO专利数据库检索分析",
    "academic-paper-composer": "学术论文撰写：从大纲到终稿",
    "academic-paper-strategist": "论文策略：选题/期刊选择/投稿",
    "define-goal": "帮助定义精确化任务目标",
    "getting-started": "为项目生成快速上手指南",
    "doc-coauthoring": "协作文档撰写：多人编辑版本追踪",
    "content-and-copy": "创建品牌内容和营销文案",
    "content-repurposing": "将内容改编为不同格式平台版本",
    "content-strategy": "制定内容策略：规划/日历/评估",
    "long-form-content-frameworks": "长文写作框架：结构/节奏/论证",
    "last30days": "研究过去30天内各平台对任意话题的真实讨论和热度",
    "standup-solo": "为个人生成每日工作汇报",
    "ship-decision": "发布决策：评估风险/准备/回滚",
    "postmortem-solo": "项目事后复盘分析",
    "launch-tweet": "为产品发布起草高质量推文",
    "domain-name-brainstormer": "为品牌/项目头脑风暴域名",
    "competitive-ads-extractor": "提取分析竞品广告素材策略",
    "superpowers-zh": "超级力量中文版：Agent能力增强",
    "paperjsx": "Office文档生成器：从JSON输入生成PPTX/DOCX/XLSX/PDF报告",
    "geju": "格局判断：大胆假设小心求证，用8种破局招式打开设计空间输出高杠杆论点",
    "snake-perspective": "从不同角度重新审视问题",
    "slug-generator": "生成简短易读的URL短链接",

    "baoyu-article-illustrator": "文章配图：根据文章内容自动生成匹配插画",
    "baoyu-danger-gemini-web": "Gemini图像文字生成：通过逆向Gemini Web API生成图像和文字",
    "baoyu-danger-x-to-markdown": "X/Twitter转Markdown：将推文串转为结构化文档",
    "baoyu-image-cards": "信息图卡片系列：12种视觉风格/8种布局/3套配色，将内容拆为1-10张信息图卡片",
    "baoyu-imagine": "多平台AI图像生成：支持OpenAI/Azure/Google/DashScope/GLM/MiniMax/Jimeng等模型",
    "blueprint": "蓝图规划：为复杂任务生成结构化执行蓝图",
    "brand-guidelines": "Anthropic品牌视觉：应用Anthropic官方色彩和字体到各类产出物",
    "career-ops": "职业运营：简历优化/面试准备/职业规划",
    "content-guard": "内容质量门禁：6道关卡检测批量文件修改前后的内容退化",
    "content-hash-cache-pattern": "内容哈希缓存：对重复内容去重，避免重复处理相同材料",
    "content-research-writer": "研究型写作：调研→引用→改进标题→引入论据，产出高质量内容",
    "content-reverse": "内容逆向拆解：全量导出公众号/抖音/B站/小红书内容，10维拆解提炼情绪句式并合成音频",
    "create-plan": "编码任务规划：为编程任务创建简洁的分步执行计划",
    "customer-billing-ops": "客户账单运营：订阅管理/退款/流失处理/账单门户运营",
    "dashboard-builder": "仪表盘构建：创建数据可视化监控面板",
    "dbs-content": "DBS内容创作诊断：用DBS框架分析内容质量",
    "email-ops": "邮箱工作流：邮件分诊/草拟/发送验证/跟进管理",
    "fal-ai-media": "AI媒体生成：通过fal.ai生成图像/视频/音频",
    "finance-billing-ops": "收入分析工作流：收入/定价/退款/团队账单模型分析",
    "helium-mcp": "氦气搜索：实时新闻/股票/ETF/加密货币数据搜索",
    "internal-comms": "内部沟通写作：3P更新/公司通讯/FAQ/状态报告/领导更新/事故报告",
    "jupyter-notebook": "Jupyter笔记本：创建和运行数据分析笔记本",
    "lead-intelligence": "销售线索分析：分析潜在客户信息和转化机会",
    "liquid-glass-design": "毛玻璃UI设计：创建磨砂玻璃质感现代界面",
    "messages-ops": "实时消息工作流：读取短信/DM/验证码/线程检查和回复",
    "notion-knowledge-capture": "Notion知识捕获：将信息快速存入Notion知识库",
    "notion-meeting-intelligence": "Notion会议准备：收集背景资料/起草议程/预读材料",
    "notion-research-documentation": "Notion研究文档：结构化记录研究过程和发现",
    "notion-spec-to-implementation": "Notion需求到实现：从产品规格到开发任务分解",
    "planning-with-files": "文件式规划：用Markdown文件做项目规划和追踪",
    "product-capability": "PRD转能力计划：将产品需求转化为可实施的能力方案",
    "project-flow-ops": "项目执行流：GitHub+Linear双平台issue/PR分诊和工作联动",
    "research-ops": "实时调研工作流：证据优先的事实调研/对比/丰富/建议生成",
    "scientific-db-pubmed-database": "PubMed文献检索：搜索和管理生物医学文献",
    "scientific-db-uspto-database": "USPTO专利检索：搜索和分析美国专利数据",
    "seo": "SEO全链路：技术SEO/页面优化/结构化数据/Core Web Vitals/内容策略审计和实施",
    "slack-gif-creator": "Slack动图：为Slack制作GIF表情和动态贴纸",
    "social-graph-ranker": "社交图谱排序：分析社交关系网并排序影响力",
    "task-capsule-builder": "任务胶囊：为目标定义约束/完成标准/风险等级",
    "team-builder": "团队构建：根据任务需求匹配合适的团队角色",
    "theme-factory": "主题工厂：批量生成配色方案和设计主题",
    "understand": "代码理解：生成交互式知识图谱理解项目结构",
    "understand-diff": "变更理解：分析Git diff/PR理解变更意图",
    "unified-notifications-ops": "统一通知：聚合多渠道通知到一处管理",
    "videodb": "视频理解平台：导入/理解/分析视频和音频内容，支持本地文件和流媒体",
    "visa-doc-translate": "签证文件翻译：专业签证/移民材料翻译",
    "wewrite": "公众号创作：从选题到发布的公众号全流程助手",
    "windows-file-system-organizer": "文件整理：智能整理磁盘文件和清理重复内容",
    "windows-performance-optimizer": "Windows优化：诊断并优化CPU/内存/磁盘/进程性能",
    "yeet": "Git一键流程：stage+commit+push+创建PR，通过gh CLI一次性完成",
    "investor-materials": "投资人材料制作：PPT/备忘录/财务模型/一页纸摘要",
    "investor-outreach": "投资人沟通：个性化邮件撰写和跟进策略",
    "dbs": "DBS工具箱入口：自动识别用户意图并路由到正确的DBS诊断/学习/决策skill",
    "dbs-chatroom-austrian": "奥派经济学聊天室：模拟哈耶克/米塞斯/Claude三角色讨论经济问题",
    "dbs-content-system": "内容系统搭建：将本地内容资产搭建成可持续生长的结构化内容工程",
    "dbs-hook": "短视频开头优化：诊断开头问题并生成可执行优化方案(5秒独立吸引力)",
    "dbs-resonate": "文稿共鸣诊断：用传播心理学框架诊断内容能否打中受众",
    "dbs-restore": "诊断状态恢复：从本地拉出最近一次诊断存档，恢复对话上下文",
    "dbs-spread": "传播心理解码：用5个经典传播学理论分析内容共鸣机制",
    "dbs-wechat-html": "公众号HTML排版：将Markdown文稿转为可直接粘贴到微信公众号后台的HTML",
    "nuwa-skill": "女娲造人：输入人名/主题提炼思维框架，构建可运行的认知操作系统Skill",

    "dbs-chatroom": "定向聊天室：根据话题推荐或指定专家，模拟多角色对话讨论",
    "brand-voice": "品牌语调提炼：从真实帖子/文章/发布说明中提取写作风格特征，建立品牌语调档案",
    "taste-skill": "前端品味设计：落地页/作品集/改版的去套路化前端设计，追求质感而非模板",
    "media-use": "媒体资产管理：一站式解决BGM/音效/图片/图标需求，本地文件+台账记录",
    "embedded-captions": "嵌入式字幕：为口播视频添加32种视觉风格的字幕，支持列流和双引擎",
    "faceless-explainer": "无脸解说视频：将文章/笔记/话题转为约3分钟的无脸解说视频",
    "youtube-downloader": "YouTube下载：自定义质量和格式下载YouTube视频",
    "lead-research-assistant": "销售线索挖掘：分析业务和ICP匹配高质量潜在客户",
    "hyperframes-animation": "HyperFrames动画知识库：原子运动规则/多阶段场景蓝图/场景转场",
    "hyperframes-core": "HyperFrames组合契约：构建一个可渲染项目，组合结构和渲染规则",
    "hyperframes-creative": "HyperFrames创意方向：视频设计规范/帧设计/非动画创意指导",
    "hyperframes-media": "HyperFrames媒体资产：音频和媒体素材，由共享音频管线生产",
    "remotion-to-hyperframes": "Remotion迁移：将Remotion(React)项目移植到HyperFrames HTML",}

# === 中文分类名 ===
CN_CATS = {
    "写作": ("写作生成", ["article-writing","viral-writer-skill","content-engine","content-creation-workflow",
               "khazix-writer","internal-comms","content-and-copy","content-repurposing",
               "content-strategy","long-form-content-frameworks","content-guard","content-hash-cache-pattern",
               "content-reverse","seo","crosspost","content-research-writer"]),
    "文本优化": ("文本优化", ["stop-slop","ai-taste-check","humanizer","shuorenhua","prompt-optimizer",
                    "faith-humanizer","faith-prompt-compile","faith-truth-check"]),
    "设计创意": ("设计创意", ["figma","figma-implement-design","figma-generate-design",
                    "frontend-design","canvas-design","brand-guidelines","brand-voice",
                    "theme-factory","liquid-glass-design","algorithmic-art","paperjsx",
                    "taste-skill","guizang-social-card-skill"]),
    "图像媒体": ("图像媒体", ["baoyu-image-gen","baoyu-cover-image","baoyu-compress-image",
                    "baoyu-comic","baoyu-illustrator","baoyu-image-cards","baoyu-imagine",
                    "baoyu-xhs-images","baoyu-infographic","ian-xiaohei-illustrations",
                    "screenshot","fal-ai-media","media-use","slack-gif-creator"]),
    "视频制作": ("视频制作", ["manim-video","remotion-video-creation","video-editing",
                    "general-video","slideshow","talking-head-recut","motion-graphics",
                    "product-launch-video","music-to-video","pr-to-video","website-to-video",
                    "hyperframes","hyperframes-animation","hyperframes-core",
                    "hyperframes-creative","hyperframes-media",
                    "remotion-to-hyperframes","blender-motion-state-inspection",
                    "baoyu-youtube-transcript","jacky-motion","faceless-explainer",
                    "embedded-captions","youtube-downloader","transcribe","speech","videodb"]),
    "社交媒体": ("社交媒体", ["baoyu-post-to-wechat","baoyu-post-to-x","baoyu-post-to-weibo",
                    "baoyu-wechat-summary","baoyu-slide-deck","dbs-wechat-html","dbs-xhs-title"]),
    "文档处理": ("文档处理", ["pdf","pptx","xlsx","docx","spreadsheets","presentations","documents",
                    "nutrient-document-processing","baoyu-format-markdown","baoyu-markdown-to-html",
                    "baoyu-url-to-markdown","baoyu-danger-x-to-markdown","baoyu-diagram",
                    "baoyu-translate","visa-doc-translate","weread-exporter","weread-skills"]),
    "研究分析": ("研究分析", ["deep-research","market-research","exa-search","search-first",
                    "hv-analysis","lead-intelligence","lead-research-assistant","research-ops",
                    "scientific-thinking-literature-review","scientific-thinking-scholar-evaluation",
                    "pubmed-database","uspto-database","academic-paper-composer","academic-paper-strategist"]),
    "商业运营": ("商业运营", ["email-ops","email-customer","investor-materials","investor-outreach",
                    "product-capability","project-flow-ops","carrier-relationship-management",
                    "customer-billing-ops","customs-trade-compliance","energy-procurement",
                    "finance-billing-ops","inventory-demand-planning","logistics-exception-management",
                    "production-scheduling","quality-nonconformance","returns-reverse-logistics",
                    "messages-ops","unified-notifications-ops","competitive-ads-extractor",
                    "domain-name-brainstormer","last30days","standup-solo","ship-decision",
                    "postmortem-solo","launch-tweet","getting-started","doc-coauthoring"]),
    "知识思维": ("知识思维", ["dbs","dbs-action","dbs-decision","dbs-goal","dbs-learning",
                    "dbs-report","dbs-save","dbs-restore","dbs-hook","dbs-chatroom",
                    "dbs-chatroom-austrian","dbs-content-system","dbs-diagnosis","dbs-deconstruct",
                    "dbs-good-question","dbs-slowisfast","dbs-resonate","dbs-spread",
                    "dbs-ai-check","faith-booknote","faith-viral-write","faith-session",
                    "faith-skill-architect","faith-skill-deploy","faith-skill-distill",
                    "faith-skill-factory","faith-skill-solution","faith-kb-scan",
                    "faith-pipeline","faith-pipeline-audit","faith-gate-check",
                    "faith-index","faith-workflow","faith-context-compress",
                    "ljg-think","ljg-writes","ljg-book","ljg-card","ljg-invest",
                    "ljg-learn","ljg-paper","ljg-present","ljg-qa","ljg-read",
                    "ljg-relationship","ljg-roundtable","ljg-skill-map","ljg-travel",
                    "ljg-word","ljg-paper-flow","ljg-paper-river","ljg-plain",
                    "ljg-push","ljg-rank","ljg-word-flow","geju","snake-perspective",
                    "knowledge-ops","knowledge-base","session-memory","define-goal",
                    "neat-freak","nuwa-skill","storage-analyzer","aihot","feishu",
                    "superpowers-zh","slug-generator","hv-analysis"]),
}

# === 触发提示词 ===
TRIGGERS = {
    "stop-slop": "检查这段内容是否存在AI废话和空洞表达,逐个标注并精简",
    "ai-taste-check": "对这篇内容做AI味深度诊断，拆根因给对策出成品附自检报告",
    "humanizer": "把这段文字去AI味,消除机器翻译感和重复句式,改得更自然",
    "shuorenhua": "对这篇进行去AI痕迹改写,降低查重率,让文风更像人写的",
    "prompt-optimizer": "优化这段提示词,使其更精准高效,分析优化前后差异",
    "article-writing": "根据这些资料写一篇深度长文,保持逻辑严密和可读性",
    "viral-writer-skill": "基于这个话题写有传播力的社交媒体文,注意标题和节奏",
    "content-engine": "为[平台]创建原生内容系统，含多平台复用策略",
    "content-creation-workflow": "用v6全流程完成这篇内容:搜索+红队+去AI味+质检+主编协作",
    "crosspost": "把这篇内容适配后分发到X/LinkedIn/Threads/Bluesky",
    "baoyu-post-to-wechat": "将这篇内容发布到微信公众号,含封面和摘要",
    "baoyu-post-to-x": "将这篇内容发布到X,支持推文和Articles长文",
    "baoyu-post-to-weibo": "将这篇内容发布到微博,支持普通帖和头条文章",
    "baoyu-translate": "用[快速/标准/高级]模式翻译这篇文章",
    "baoyu-cover-image": "为这篇文章生成封面图:指定类型/配色/渲染/文字/情绪",
    "baoyu-image-gen": "[已废弃]建议使用baoyu-imagine替代",
    "baoyu-comic": "把这个故事/脚本生成漫画分镜和画面",
    "baoyu-diagram": "创建暗色主题SVG图表:架构图/流程图/序列图等",
    "baoyu-infographic": "将这份数据/信息制作成信息图,突出关键结论",
    "baoyu-slide-deck": "从这份内容生成幻灯片:大纲+风格设定+逐页卡片图片",
    "baoyu-format-markdown": "将文本格式化为规范Markdown,优化标题层级和排版",
    "baoyu-markdown-to-html": "将Markdown转为微信公众号兼容HTML",
    "baoyu-url-to-markdown": "抓取这个URL内容转为结构化Markdown",
    "baoyu-wechat-summary": "帮我整理这个微信群的聊天亮点和结构化摘要",
    "baoyu-compress-image": "压缩这张图片到指定大小,保持画质减小文件",
    "baoyu-youtube-transcript": "下载这个YouTube视频的字幕并总结要点",
    "baoyu-xhs-images": "[已废弃]建议使用baoyu-image-cards替代",
    "deep-research": "对[主题]深度调研,多源验证,输出研究报告",
    "market-research": "对[市场/赛道]做竞争分析,含主要玩家和趋势",
    "exa-search": "用神经搜索找关于[主题]的最新资料",
    "search-first": "执行操作前先搜索确认最佳实践和最新方案",
    "figma": "Figma设计上下文：获取设计稿/截图/变量/素材，支持设计稿转前端代码",
    "frontend-design": "根据描述创建前端页面,含交互和动画",
    "canvas-design": "在Canvas创建视觉设计/海报",
    "manim-video": "生成[主题]的数学/科学动画视频",
    "remotion-video-creation": "用React代码创建编程视频/动画",
    "video-editing": "编辑视频:剪切/合并/字幕/转场",
    "transcribe": "将这段音频/视频转录为文字,带时间戳",
    "speech": "将这段文字转为自然语音朗读",
    "general-video": "创建通用视频:口播/教程/宣传片",
    "slideshow": "创建16:9幻灯片视频,带转场和背景音乐",
    "talking-head-recut": "对口播视频精剪,优化节奏和画面",
    "motion-graphics": "创建MG动画/动态图形,品牌展示或产品介绍",
    "product-launch-video": "制作产品发布宣传视频,含功能演示",
    "pdf": "处理这个PDF:读取/提取/合并/格式转换",
    "pptx": "创建/编辑PPT演示文稿:布局/图表/动画",
    "xlsx": "处理Excel表格:数据分析/图表/公式",
    "docx": "创建/编辑Word文档:排版/目录/审阅",
    "documents": "创建/编辑文档,支持多格式协作",
    "jacky-motion": "把这篇口播稿变成16:9信息动画HTML",
    "guizang-social-card-skill": "为这个话题生成小红书风格卡片",
    "khazix-writer": "以卡兹克风格写这篇公众号长文",
    "neat-freak": "任务完成后运行,自动对齐代码/文档/记忆,输出变更摘要",
    "hv-analysis": "对[产品/公司/概念]做横纵分析,输出万字报告",
    "storage-analyzer": "扫描磁盘空间使用,三色分级显示清理建议",
    "aihot": "查询今天的AI热点日报",
    "feishu": "通过飞书API操作:发消息/读写文档/管理群组",
    "dbs": "用DBS核心框架:决策/学习/记忆/目标管理",
    "faith-booknote": "提取这本书核心观点形成结构化读书笔记",
    "ljg-think": "多维度深度思考[问题],输出结构化分析",
    "ljg-writes": "用结构化方法写作[主题]",
    "ljg-book": "深度拆解解读[书名]这本书",
    "academic-paper-composer": "根据研究资料撰写学术论文,从大纲到终稿",
    "define-goal": "帮我把[模糊需求]定义为精确可执行的目标",
    "snake-perspective": "从不同角度重新审视这个[问题/方案]",
    "geju": "用格局判断打开这个方案的设计空间，输出破局论点",
    "investor-materials": "制作投资人材料:PPT/备忘录/财务模型",
    "investor-outreach": "面向投资人写个性化邮件和跟进策略",
    "email-ops": "批量管理邮件运营:发送/模板/追踪",
    "session-memory": "回顾之前的讨论和决策,确保上下文连贯",

    "baoyu-article-illustrator": "根据这篇文章内容自动生成匹配的插画配图",
    "baoyu-danger-gemini-web": "用Gemini Web API生成图像或文字内容",
    "baoyu-danger-x-to-markdown": "把这个推文串转成结构化Markdown文档",
    "baoyu-image-cards": "把这段内容做成信息图卡片系列(指定风格/布局/配色)",
    "baoyu-imagine": "用[指定模型]根据这个描述生成图像",
    "blueprint": "为这个复杂任务生成结构化执行蓝图",
    "brand-guidelines": "按Anthropic品牌色彩和字体规范处理这份产出物",
    "career-ops": "帮我优化简历并为这个岗位做面试准备",
    "content-guard": "对本次批量文件修改执行6道内容质量门禁检查",
    "content-hash-cache-pattern": "对这批内容做哈希去重,跳过已处理的重复材料",
    "content-research-writer": "围绕[主题]做研究型调研写作,带引用和数据支撑",
    "content-reverse": "全量导出并10维逆向拆解这个账号的内容，提炼情绪句式",
    "create-plan": "为这个编程任务创建分步执行计划",
    "customer-billing-ops": "处理订阅/退款/客户流失/账单门户运营",
    "dashboard-builder": "为这个数据创建可视化监控仪表盘",
    "dbs-content": "用DBS框架诊断这篇内容的创作质量",
    "email-ops": "对这组邮件做分诊/草拟/发送验证/跟进管理",
    "fal-ai-media": "用fal.ai生成[图像/视频/音频]素材",
    "finance-billing-ops": "分析收入/定价/退款/团队账单模型",
    "helium-mcp": "搜索最新的实时新闻/股票/ETF/加密货币数据",
    "internal-comms": "帮我写3P更新/公司通讯/FAQ/状态报告/事故报告",
    "jupyter-notebook": "创建数据分析Jupyter笔记本并运行",
    "lead-intelligence": "分析这个潜在客户的信息和转化机会",
    "liquid-glass-design": "创建毛玻璃风格UI界面,磨砂透明现代感",
    "messages-ops": "读取这些短信/DM/验证码并检查相关线程",
    "notion-knowledge-capture": "把这些信息快速存入Notion知识库",
    "notion-meeting-intelligence": "为这次会议准备背景资料/议程/预读材料到Notion",
    "notion-research-documentation": "结构化记录这个研究过程和发现到Notion",
    "notion-spec-to-implementation": "把这个产品规格分解为开发任务存到Notion",
    "planning-with-files": "用Markdown文件做这个项目的规划和进度追踪",
    "product-capability": "把这个PRD转化为可实施的能力计划",
    "project-flow-ops": "在GitHub+Linear上分诊issue/PR并联动工作",
    "research-ops": "对[主题]做证据优先的实时调研和对比分析",
    "scientific-db-pubmed-database": "在PubMed中检索这个课题的生物医学文献",
    "scientific-db-uspto-database": "在USPTO专利库中搜索相关专利",
    "seo": "审计并优化这个网站的技术SEO/页面优化/结构化数据/性能",
    "slack-gif-creator": "为Slack制作这个表情GIF动图",
    "social-graph-ranker": "分析这个社交关系网并按影响力排序",
    "task-capsule-builder": "为这个目标定义约束/完成标准和风险等级",
    "team-builder": "根据这个任务需求匹配合适的团队角色配置",
    "theme-factory": "为这个项目生成3套配色方案和设计主题",
    "understand": "分析这个项目的代码结构生成交互式知识图谱",
    "understand-diff": "分析这次代码变更的意图和影响范围",
    "unified-notifications-ops": "聚合这些分散的通知到一处集中查看",
    "videodb": "导入这段视频/音频进行分析和理解",
    "visa-doc-translate": "翻译这份签证/移民文件,保持专业术语准确",
    "wewrite": "从选题到发布,帮我在公众号完成这篇内容的全流程",
    "windows-file-system-organizer": "扫描并智能整理C盘/D盘的文件和清理重复内容",
    "windows-performance-optimizer": "诊断并优化Windows系统性能:CPU/内存/磁盘/进程",
    "yeet": "一键stage+commit+push并创建GitHub PR",
    "last30days": "搜索过去30天内关于[话题]的全网真实讨论和热度(Reddit/X/YouTube/TikTok等)",
    "dbs": "用DBS工具箱处理[需求]，自动路由到合适的诊断skill",
    "dbs-chatroom-austrian": "用奥派经济学视角讨论[经济话题]",
    "dbs-content-system": "把我的本地内容资产搭建成结构化内容系统",
    "dbs-hook": "诊断这个短视频开头有什么问题并生成优化方案",
    "dbs-resonate": "诊断这段文稿能否在传播心理上引起受众共鸣",
    "dbs-restore": "恢复我上次的诊断存档，接着继续讨论",
    "dbs-spread": "用传播学理论分析这段内容为什么能引起共鸣",
    "dbs-wechat-html": "把这篇Markdown转成微信公众号HTML排版",
    "nuwa-skill": "提炼[人物/主题]的思维框架，构建可运行的认知操作系统",


    "dbs-chatroom": "开启定向聊天室，让[专家列表]多角色讨论[话题]",
    "brand-voice": "从这些内容中提炼品牌语调特征，建立写作风格档案",
    "taste-skill": "为这个页面/作品集做去套路化前端设计，追求质感和品味",
    "media-use": "为这个项目匹配BGM/音效/图片/图标等媒体素材",
    "embedded-captions": "为这个口播视频添加[风格名]字幕效果",
    "faceless-explainer": "把这篇内容转成无脸解说视频(约3分钟)",
    "youtube-downloader": "下载这个YouTube视频[指定质量/格式]",
    "lead-research-assistant": "为我的产品分析并匹配高质量潜在客户",
    "hyperframes-animation": "用HyperFrames为这个场景设计动画规则和转场",
    "hyperframes-core": "用HyperFrames组合契约构建可渲染项目",
    "hyperframes-creative": "为这个HyperFrames视频做创意方向和设计规范",
    "hyperframes-media": "为HyperFrames项目生成音频和媒体素材",
    "remotion-to-hyperframes": "把这个Remotion项目移植到HyperFrames HTML",}


# === Build ===
def load_skills():
    skills = {}
    for root in roots:
        if not root.exists(): continue
        for sd in sorted(root.iterdir()):
            if not sd.is_dir() or sd.name.startswith("."): continue
            if sd.name in ("solo-skills","rampstack","_archived",".archived",".system"): continue
            sm = sd / "SKILL.md"
            if not sm.exists(): continue
            name = sd.name
            if name in EXCLUDE_PATTERNS: continue
            try: text = sm.read_text(encoding="utf-8")
            except: continue
            
            desc = ""
            parts = []
            if text.startswith("---"):
                parts = text.split("---",2)
                if len(parts)>=3:
                    for line in parts[1].strip().split("\n"):
                        if ":" in line:
                            k,v = line.split(":",1)
                            if k.strip()=="description": desc = v.strip().strip("\"'")
            
            if not desc:
                body = parts[2].strip() if len(parts)>=3 else text.strip()
                body = re.sub(r"<[^>]+>","",body)
                ls = [l.strip().lstrip("#").strip() for l in body.split("\n") if l.strip() and not l.startswith("---")]
                desc = ls[0][:100] if ls else ""
            
            desc = re.sub(r"\s+"," ",desc).strip()[:100]
            skills[name] = desc
    return skills

skills = load_skills()

# Assign categories
by_cat = defaultdict(list)
for name in sorted(skills):
    found = False
    for ccat, (clabel, clist) in CN_CATS.items():
        if name in clist:
            by_cat[ccat].append(name)
            found = True
            break
    if not found:
        by_cat["其他"].append(name)

# Generate markdown
out = []
out.append("# Skills 快捷手册")
out.append("")
out.append(f"> 应用型 Skill 合集 · {len(skills)} 个 · 不含开发编码类")
out.append("")

# Index
out.append("## 分类")
out.append("")
for ccat in list(CN_CATS.keys())+["其他"]:
    if ccat in by_cat:
        names = by_cat[ccat]
        label = CN_CATS.get(ccat,(ccat,))[0]
        items = " ".join(f"`{n}`" for n in names)
        out.append(f"- **{label}** ({len(names)}): {items}")

out.append("")
out.append("---")

# Detail sections
for ccat in list(CN_CATS.keys())+["其他"]:
    if ccat not in by_cat: continue
    label = CN_CATS.get(ccat,(ccat,))[0]
    out.append(f"## {label}")
    out.append("")
    out.append("| 技能 | 作用 | 触发提示词 |")
    out.append("|---|---|---|")
    for name in sorted(by_cat[ccat]):
        cn_name = CN_NAMES.get(name, name)
        cn_desc = CN_DESC.get(name, skills.get(name,"")[:80])
        trigger = TRIGGERS.get(name, f"使用{cn_name}的完整能力处理[任务]")
        cn_desc = cn_desc.replace("|","·")
        trigger = trigger.replace("|","·")
        out.append(f"| **{cn_name}** `{name}` | {cn_desc} | {trigger} |")
    out.append("")

out.append("---")
out.append(f"\n*{len(skills)} 个应用技能 · 2026-07-05*")

Path("D:/KnowledgeBase/skills-quick-reference.md").write_text("\n".join(out), encoding="utf-8")
print(f"Done: {len(skills)} skills in {len(by_cat)} categories")